spring:
  datasource:
    url: ${{ secrets.RDS_URL }}
    username: ${{ secrets.DB_USERNAME }}
    password: ${{ secrets.DB_PASSWORD }}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

chatGpt:
  key: ${{ secrets.chatGpt_key }}

openweathermap:
  key: ${{ secrets.OPENWEATHERMAP_KEY }}
